# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "deepmased_predict"
description: |
  Predict misassemblies in metagenomic assemblies using pre-trained deep learning models.
  This process takes feature vectors extracted by deepmased/features and applies a
  convolutional neural network (CNN) to predict potential misassembly locations along
  each contig.

keywords:
  - metagenomics
  - assembly
  - quality control
  - prediction
  - deep learning
  - misassembly
  - machine learning

tools:
  - deepmased:
      description: |
        Deep learning for Metagenome Assembly Error Detection. This module runs the
        'predict' subcommand which applies pre-trained CNN models to feature vectors
        to identify likely misassembly locations. The model predicts misassembly
        probabilities for sliding windows along each contig.
      homepage: https://github.com/leylabmpi/DeepMAsED
      documentation: https://github.com/leylabmpi/DeepMAsED/blob/master/README.md
      tool_dev_url: https://github.com/leylabmpi/DeepMAsED
      doi: "10.1093/bioinformatics/btaa124"
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample1', single_end: false]
  - feature_path_file:
      type: file
      description: |
        TSV file containing paths to feature files generated by deepmased/features.
        This file lists the locations of individual feature files for each contig.
      pattern: "*_feature_file_paths.tsv"
  - feature_file:
      type: file
      description: |
        TSV file with extracted feature vectors for each contig, generated by
        deepmased/features. Contains numerical feature values used for prediction.
      pattern: "*_feats.tsv"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample1', single_end: false]
  - predictions:
      type: file
      description: |
        TSV file with misassembly predictions for each contig. Contains columns:
        - contig_id: Name of the contig
        - position: Position along the contig (bp)
        - prediction: Misassembly probability (0-1)
        - prediction_binary: Binary classification (0=correct, 1=misassembly)
        Higher prediction values indicate higher likelihood of misassembly.
      pattern: "*_predictions.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@your_github_username"
maintainers:
  - "@your_github_username"

notes:
  - |
    This process requires feature files generated by deepmased/features as input.
  - |
    The prediction uses pre-trained CNN models included in the DeepMAsED package.
  - |
    Predictions are made in sliding windows along each contig.
  - |
    The process runs in CPU-only mode by default (--cpu-only flag) for better compatibility.
  - |
    Higher prediction scores indicate regions more likely to contain misassemblies.
  - |
    Typical usage is to filter predictions by a threshold (e.g., >0.5 or >0.7) to identify
    high-confidence misassembly predictions.
  - |
    The binary predictions use an internal threshold optimized during model training.